#ifndef SYNTAXTREETYPE_HPP
#define SYNTAXTREETYPE_HPP

enum SyntaxTreeType
{
    SYN_ASSIGNMENT, SYN_BINARY, SYN_CALL,
    SYN_IDENTIFIER, SYN_IF, SYN_NUMBER,
    SYN_PRINT, SYN_PROGRAM, SYN_STRING
};

#endif